#!/bin/sh

if [ ${CONFIGURATION} == "Debug" ]; then

    BUILD_NUMBER=`git rev-list HEAD --count`
    INFO_PLIST="${SRCROOT}/${INFOPLIST_FILE}"

    /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "$INFO_PLIST"
#    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${FrameworkBundleVersion}" "$INFO_PLIST"

fi
